let role=null,peer=null,conn=null,roomCode='',myId='';let hostPeers=[];let state={questions:[],qIndex:-1,questionOpen:false,buzzes:[],currentAnswering:null,players:[],rules:{correctPoints:10,wrongPoints:0,agariScore:100,tobiWrongLimit:3,tobiPenaltyQuestions:0}};const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.add('hidden'),2200)}function beep(f=700,ms=120,type='sine'){try{const C=window.AudioContext||window.webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.type=type;g.gain.value=.12;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+ms/1000)}catch(e){}}function speak(t){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='ja-JP';u.rate=.95;speechSynthesis.speak(u)}function broadcast(){hostPeers=hostPeers.filter(c=>c.open);hostPeers.forEach(c=>c.send({type:'state',state}))}function scoreHTML(){return state.players.slice().sort((a,b)=>b.score-a.score).map((p,i)=>`<div class="scoreRow"><span>${i+1}. <b>${esc(p.name)}</b></span><span>${p.score}点 ${p.agari?'🎉':p.tobi?'🚫':''}</span></div>`).join('')||'<p class="muted">参加者を待っています…</p>'}
async function makeHost(){role='host';roomCode=Math.random().toString(36).slice(2,8).toUpperCase();peer=new Peer(roomCode);peer.on('open',()=>{$('hostCode').textContent=roomCode;$('home').classList.add('hidden');$('host').classList.remove('hidden');$('conn').textContent='● 大会ホスト中';toast('部屋を作成しました！')});peer.on('error',e=>{if(e.type==='unavailable-id'){roomCode=Math.random().toString(36).slice(2,8).toUpperCase();peer.destroy();makeHost()}else alert('接続エラー: '+e.type)});peer.on('connection',c=>{c.on('open',()=>{hostPeers.push(c);c.send({type:'state',state})});c.on('data',d=>{if(d.type==='join'){if(state.players.some(p=>p.id===c.peer))return;state.players.push({id:c.peer,name:String(d.name).slice(0,30),score:0,wrong:0,agari:false,tobi:false,disabledUntilQ:-1});broadcast();render()}if(d.type==='buzz'){const p=state.players.find(p=>p.id===c.peer);if(!p||!state.questionOpen||state.currentAnswering||p.agari||p.tobi||p.disabledUntilQ>=state.qIndex)return;state.buzzes.push({name:p.name,playerId:p.id});state.currentAnswering=p.id;state.questionOpen=false;beep(620,150,'square');broadcast();render()}});c.on('close',()=>{hostPeers=hostPeers.filter(x=>x!==c);state.players=state.players.filter(p=>p.id!==c.peer);render();broadcast()})})}
$('createBtn').onclick=makeHost;$('copyCodeBtn').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode)}catch(e){}toast('部屋コードをコピーしました')};$('joinCode').oninput=e=>e.target.value=e.target.value.replace(/[^a-z0-9]/gi,'').toUpperCase();$('joinBtn').onclick=()=>{roomCode=$('joinCode').value.trim().toUpperCase();const name=$('joinName').value.trim();if(roomCode.length<4||!name)return alert('部屋コードと名前を入力してください');role='player';$('playerCode').textContent=roomCode;peer=new Peer();peer.on('open',id=>{myId=id;conn=peer.connect(roomCode,{reliable:true});conn.on('open',()=>{conn.send({type:'join',name});$('home').classList.add('hidden');$('player').classList.remove('hidden');$('conn').textContent='● 接続済み';toast('参加しました！')});conn.on('data',d=>{if(d.type==='state'){state=d.state;render()}});conn.on('close',()=>toast('ホストとの接続が切れました'))});peer.on('error',()=>alert('部屋が見つからないか、接続できませんでした'))};
function normalizeCell(v){return String(v??'').replace(/^\uFEFF/,'').trim()}
function findColumn(headers,names){const normalized=headers.map(normalizeCell).map(x=>x.toLowerCase());for(const n of names){const i=normalized.indexOf(n.toLowerCase());if(i>=0)return i}return -1}
function parseQuestionFile(wb){
  const ws=wb.Sheets[wb.SheetNames[0]];
  const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false,blankrows:false});
  const rows=matrix.map(r=>r.map(normalizeCell)).filter(r=>r.some(Boolean));
  if(!rows.length)return {questions:[],reason:'データが空です'};
  const aliases={q:['問題','問題文','question','questions','questiontext'],a:['答え','正解','answer','answers'],c:['ジャンル','カテゴリ','category'],p:['得点','ポイント','points','point']};
  let headerIndex=-1, qCol=-1, aCol=-1, cCol=-1, pCol=-1;
  for(let i=0;i<Math.min(rows.length,5);i++){
    const r=rows[i];
    const qi=findColumn(r,aliases.q), ai=findColumn(r,aliases.a);
    if(qi>=0 && ai>=0){headerIndex=i;qCol=qi;aCol=ai;cCol=findColumn(r,aliases.c);pCol=findColumn(r,aliases.p);break}
  }
  // Headerless CSV: use the first non-empty column as question and the next as answer.
  if(headerIndex<0){
    headerIndex=-1;
    const maxCols=Math.max(...rows.map(r=>r.length));
    for(let i=0;i<rows.length;i++){
      const r=rows[i];
      if(r.length>=2 && r.filter(Boolean).length>=2){
        qCol=0;aCol=1;
        if(!r[0] && r[1]){qCol=1;aCol=2}
        break;
      }
    }
    if(qCol<0)return {questions:[],reason:'「問題・答え」の2列を認識できませんでした'};
  }
  const data=rows.slice(headerIndex+1).map(r=>({
    question:normalizeCell(r[qCol]),
    answer:normalizeCell(r[aCol]),
    category:cCol>=0?normalizeCell(r[cCol]):'',
    points:Number(normalizeCell(r[pCol]))||state.rules.correctPoints
  })).filter(q=>q.question);
  return {questions:data,reason:data.length?`${data.length}問を読み込みました`:`問題文の列は見つかりましたが、問題データが0件です`};
}
$('importBtn').onclick=async()=>{const f=$('fileInput').files[0];if(!f)return alert('ファイルを選択してください');try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});const result=parseQuestionFile(wb);state.questions=result.questions;$('fileMsg').textContent=result.reason;if(!result.questions.length){alert(result.reason+'\n\nCSVなら「問題,答え」の形式、または見出しなしの「問題,答え」の2列で読み込めます。');}else toast(result.reason);broadcast();render()}catch(e){console.error(e);state.questions=[];$('fileMsg').textContent='読み込みに失敗しました';alert('CSV/Excelを読み込めませんでした。ファイル形式を確認してください。')}};$('saveRules').onclick=()=>{state.rules={correctPoints:+$('correctPoints').value,wrongPoints:+$('wrongPoints').value,agariScore:+$('agariScore').value,tobiWrongLimit:+$('tobiWrongLimit').value,tobiPenaltyQuestions:+$('tobiPenaltyQuestions').value};broadcast();toast('ルールを保存しました')};$('startBtn').onclick=()=>{if(!state.questions.length)return alert('先に問題を読み込んでください');state.qIndex=0;state.questionOpen=false;state.buzzes=[];state.currentAnswering=null;broadcast();render()};$('openBtn').onclick=()=>{if(state.qIndex<0)return;state.questionOpen=!state.questionOpen;if(state.questionOpen){state.buzzes=[];state.currentAnswering=null}broadcast();render()};$('nextBtn').onclick=()=>{if(state.qIndex+1>=state.questions.length)return alert('最後の問題です');state.qIndex++;state.questionOpen=false;state.buzzes=[];state.currentAnswering=null;broadcast();render()};$('speakBtn').onclick=()=>{const q=state.questions[state.qIndex];if(q)speak(`第${state.qIndex+1}問。${q.question}`)};$('correctBtn').onclick=()=>judge(true);$('wrongBtn').onclick=()=>judge(false);function judge(ok){const p=state.players.find(x=>x.id===state.currentAnswering);if(!p)return;if(ok){p.score+=Number(state.questions[state.qIndex].points||state.rules.correctPoints);if(p.score>=state.rules.agariScore)p.agari=true;beep(900,180,'triangle')}else{p.score+=state.rules.wrongPoints;p.wrong++;if(p.wrong>=state.rules.tobiWrongLimit)p.tobi=true;p.disabledUntilQ=state.qIndex+state.rules.tobiPenaltyQuestions;beep(180,220,'sawtooth')}state.currentAnswering=null;state.questionOpen=false;broadcast();render()}
$('buzzBtn').onclick=()=>buzz();function buzz(){const me=state.players.find(p=>p.id===myId);if(!me||$('buzzBtn').disabled)return;conn.send({type:'buzz'})}addEventListener('keydown',e=>{if(role==='player'&&e.code==='Space'&&!e.repeat){e.preventDefault();buzz()}});function render(){if(role==='host'){$('hostPlayerCount').textContent=state.players.length+'人';$('hostQTitle').textContent=state.qIndex>=0?`第${state.qIndex+1}問 / ${state.questions.length}問`:'問題未開始';const q=state.questions[state.qIndex];$('hostQuestion').textContent=q?.question||'問題を読み込んでください';$('hostAnswer').textContent=q?.answer?'正解：'+q.answer:'';$('hostAnswer').classList.toggle('hidden',!q?.answer);$('progressFill').style.width=state.qIndex>=0?(100*(state.qIndex+1)/state.questions.length)+'%':'0%';$('buzzState').textContent=state.questionOpen?'受付中':'受付停止';$('buzzList').innerHTML=state.buzzes.length?state.buzzes.map((b,i)=>`<li>${i+1}. ${esc(b.name)}</li>`).join(''):'<li>まだありません</li>';$('hostScores').innerHTML=scoreHTML();if(state.currentAnswering){$('judge').classList.remove('hidden');$('answeringName').textContent=state.players.find(p=>p.id===state.currentAnswering)?.name||'回答者'}else $('judge').classList.add('hidden')}if(role==='player'){const me=state.players.find(p=>p.id===myId);$('playerCount').textContent=state.players.length+'人';$('playerQTitle').textContent=state.qIndex>=0?`第${state.qIndex+1}問 / ${state.questions.length}問`:'待機中';$('playerQuestion').textContent=state.questions[state.qIndex]?.question||'出題者の開始を待っています';$('playerScores').innerHTML=scoreHTML();const r=state.players.findIndex(p=>p.id===myId);$('playerRank').textContent=r>=0?'#'+(r+1):'#—';if(me){$('playerStatus').textContent=me.agari?'🎉 上がり！':me.tobi?'🚫 飛び':state.currentAnswering===myId?'🔔 あなたが回答中':state.questionOpen?'🔥 早押し受付中！':'回答者を判定中…';$('buzzBtn').disabled=!state.questionOpen||!!state.currentAnswering||me.agari||me.tobi||me.disabledUntilQ>=state.qIndex}}}
